/*
 * ETSI ISG CIM / NGSI-LD API
 *
 * This OAS file describes the NGSI-LD API defined by the ETSI ISG CIM group. This Cross-domain Context Information Management API allows to provide, consume and subscribe to context information in multiple scenarios and involving multiple stakeholders
 *
 * API version: latest
 * Contact: NGSI-LD@etsi.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type GeoQuery struct {

	Georel *Georel `json:"georel"`

	Coordinates *Coordinates `json:"coordinates"`

	Geometry *Geometry `json:"geometry"`
}
