/*
 * ETSI ISG CIM / NGSI-LD API
 *
 * This OAS file describes the NGSI-LD API defined by the ETSI ISG CIM group. This Cross-domain Context Information Management API allows to provide, consume and subscribe to context information in multiple scenarios and involving multiple stakeholders
 *
 * API version: latest
 * Contact: NGSI-LD@etsi.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models
import (
	"time"
)

type Subscription struct {

	Context *LdContext `json:"@context,omitempty"`

	Entities []EntityInfo `json:"entities,omitempty"`

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	WatchedAttributes []string `json:"watchedAttributes,omitempty"`

	TimeInterval float64 `json:"timeInterval,omitempty"`

	Expires time.Time `json:"expires,omitempty"`

	IsActive bool `json:"isActive,omitempty"`

	Throttling float64 `json:"throttling,omitempty"`

	Q string `json:"q,omitempty"`

	GeoQ *GeoQuery `json:"geoQ,omitempty"`

	Csf string `json:"csf,omitempty"`

	Id string `json:"id,omitempty"`

	Type_ string `json:"type,omitempty"`

	Notification *NotificationParams `json:"notification,omitempty"`

	Status string `json:"status,omitempty"`

	CreatedAt *time.Time `json:"createdAt,omitempty"`

	ModifiedAt *time.Time `json:"modifiedAt,omitempty"`
}

func NewSubscription() *Subscription {
	return &Subscription{}
}